name: JavaScript Build
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout repository
      uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Echo Node & NPM versions
      run: |
        node -v
        npm -v

    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Run the build
      run: |
        npm run lint
        npm run build
