name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Update release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Check out release branch
        uses: actions/checkout@v2
        with:
          ref: release
      
      - name: Merge production branch
        run: |
          git fetch origin
          git checkout -b tmp origin/main
          git merge -s ours origin/release
          git checkout release
          git merge tmp
          git branch -D tmp
      
      - name: Build code
        run: |
          npm ci
          npm run build:theme
      
      - name: Update release branch
        run: |
          git push release:release
