name: Release

on:
  workflow_run:
    workflows: [ 'JavaScript Build' ]
    types: [ 'completed' ]
    branches:
      - main
      - build-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: deploy build code to branch
    steps:
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release # The branch name where you want to push the assets.
          FOLDER: / # The top-level directory to push to the specified branch.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this.
          MESSAGE: "Build: ({sha}) {msg}" # Commit message.
